Add GA code
openspending/os-packager pull request #104
Opened 2016-12-08 14:52 UTC by kravets-levko

okfn/os-private-issues/issues/43

2016-12-18 09:02 UTC, akariv requested changes

2016-12-18 09:02 UTC, akariv commented on app/config/index.js
> +    ga: process.env.OS_SNIPPETS_GA || 'UA-33874954-42'
I would prefer that by default no GA code would be included, and not that all installations will use our GA code.

2016-12-19 08:09 UTC, kravets-levko commented on app/config/index.js
> +    ga: process.env.OS_SNIPPETS_GA || 'UA-33874954-42'
Agreed. I'll remove it from configs, but do not forget to add it when deploying app.

2016-12-19 08:23 UTC, kravets-levko commented
@akariv I've updated this and other related PRs. Can you review them again, please?

2016-12-19 11:55 UTC, merged